packages:
  - apps/web
  - apps/mobile
  - apps/server
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.21
  '@better-auth/expo': 1.6.23
  '@eslint/js': ^10.0.1
  '@tailwindcss/postcss': ^4.3.3
  '@tailwindcss/vite': ^4.3.3
  '@tanstack/react-query': ^5.101.4
  '@types/node': ^22.20.1
  '@vitejs/plugin-react': 6.0.3
  better-auth: 1.6.23
  eslint: ^10.7.0
  prettier: ^3.9.6
  tailwindcss: ^4.3.3
  typescript: ^6.0.3
  vite: 8.1.5
  zod: 4.4.3

catalogs:
  react19:
    '@types/react': ^19.2.17
    '@types/react-dom': ^19.2.3
    react: 19.2.8
    react-dom: 19.2.8

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  '@vercel/postgres': '-'
  '@expo/dom-webview': 57.0.1
  '@expo/metro-runtime': 57.0.6
  better-call: 1.3.5
  lightningcss: 1.30.1
  react: 19.2.8
  react-dom: 19.2.8
  vite: 8.1.5

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
  - react
  - react-native
  - react-dom
